name = super_give
author = daneldragondanel-boop
description = An advanced, high-performance GUI menu for granting any item registered in the game. Features dynamic search, quantity control, and live item renaming (meta-description editing). The ultimate tool for administrators and creative players.

release = 34958
title = super_give
