name = super_give
author = daneldragondanel-boop
description = This will allow you to give yourself any item in the game with one command and give it color, damage, durability, light, recharge, range, etc. 
title = super_give
release = 36769
