name = 3d_armor
depends = player_api
optional_depends = default, player_monoids, armor_monoid, pova, moreores, inventory_plus, sfinv, unified_inventory, ethereal, nether, technic, skins, u_skins, simple_skins, wardrobe, player_textures
description = 3d_armor modpack (all submods) merged into a single mod / single init.lua.
min_minetest_version = 5.4
