name = steamified
title = Steamified
description = Rotational contraptions for your world. Has a stress and RPM system.
author = spinning-cubes
optional_depends = default, mesecons_mvps, mesecons_luacontroller, digilines, sbz_luacontroller
supported_games = *
min_minetest_version = 5.14

release = 37110
